line-length = 120
target-version = "py310"

[lint]
select = ["E", "F", "I", "UP", "B", "SIM", "PLR"]
ignore = ["E501"]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
docstring-code-format = true #是否在注释中格式化代码片段
skip-magic-trailing-comma = true #使用现有的尾随逗号作为短行应保持独立的指示